# Generated by Django 2.2.3 on 2019-10-31 10:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('SystemsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistema',
            name='receptor_route_save',
        ),
        migrations.RemoveField(
            model_name='sistema',
            name='receptor_server_ip',
        ),
        migrations.RemoveField(
            model_name='sistema',
            name='receptor_server_username',
        ),
        migrations.CreateModel(
            name='CopiaRespaldo',
            fields=[
                ('id_respaldo', models.AutoField(primary_key=True, serialize=False)),
                ('receptor_server_username', models.CharField(max_length=200)),
                ('receptor_server_ip', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(re.compile('([0-9]{1,3}.?){4}'), 'ip incorrecta', 'invalid')])),
                ('receptor_route_save', models.CharField(max_length=500)),
                ('id_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemsApp.Sistema')),
            ],
        ),
    ]
