# Generated by Django 2.2.3 on 2019-11-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemsApp', '0002_auto_20191031_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistema',
            name='bd_password',
        ),
        migrations.RemoveField(
            model_name='sistema',
            name='bd_username',
        ),
        migrations.AddField(
            model_name='sistema',
            name='copy_to_drive',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='sistema',
            name='copy_to_server',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
